export type PrimaryDocumentType = "INCOME_STATEMENT" | "BALANCE_SHEET" | "CASH_FLOW_STATEMENT" | "SHAREHOLDERS_EQUITY_STATEMENT" | "STATEMENT_OPERATIONS" 

export type SecondaryDocumentType = "REVENUE_NOTES"

